nmMode: hardlinks-local

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.4.1.cjs

npmScopes:
  imchhh:
    npmPublishRegistry: https://registry.npmjs.com
    npmRegistryServer: https://registry.npmjs.com
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_TOKEN:-}"
